# Generated by Django 5.2.13 on 2026-05-11 01:07

import django.core.validators
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Bank name*')),
                ('description', models.TextField(max_length=600, verbose_name='Bank description*')),
                ('branch_name', models.CharField(max_length=50, verbose_name='Bank Branch name*')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Address line 1*')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='Address line 2')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Customer support phone number')),
                ('post_code', models.CharField(max_length=11, verbose_name='Bank postcode*')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Bank Country*')),
                ('bank_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('interest_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20, verbose_name='Interest Period*')),
                ('minimum_opening_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Minimum opening deposit*')),
                ('monthly_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monthly deposit*')),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('offer_overdraft', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Offer overdraft*')),
                ('offer_saving_account', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3, verbose_name='Offer saving accounts*')),
                ('logo', models.ImageField(null=True, upload_to='bank/logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Bank logo')),
                ('interest_rate', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Interest rate (%)*')),
                ('interest_rate_bps', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='SortCodeAllocationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('start_range', models.PositiveBigIntegerField(default=0)),
                ('end_range', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('block_start', models.PositiveBigIntegerField(default=0)),
                ('block_end', models.PositiveBigIntegerField(default=0)),
                ('last_issued_sortcode_number', models.PositiveBigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sort_codes', to='bank.bank')),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='sort_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='bank.sortcode'),
        ),
        migrations.CreateModel(
            name='SortCodeAllocationStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('start_range', models.PositiveBigIntegerField(blank=True, null=True)),
                ('end_range', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sortcode_allocation_logs', to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='SortCodeRangePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.PositiveBigIntegerField()),
                ('end_range', models.PositiveBigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_on', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_pools', to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_code', models.CharField(blank=True, max_length=8, null=True)),
                ('account_number', models.CharField(editable=False, max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_interest_run', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('savings', 'Savings')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('restricted', 'Restricted'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('interest_enabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='user_profile.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sort_code', 'account_number'), name='unique_account_per_sortcode')],
            },
        ),
    ]
