# Generated by Django 5.2.13 on 2026-05-07 14:54

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=600)),
                ('branch_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=255)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('identifier', models.CharField(blank=True, max_length=20, unique=True)),
                ('interest_period', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI_WEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('minimum_opening_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('offer_overdraft', models.BooleanField(default=False)),
                ('offer_saving_account', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to='bank/logo/')),
                ('interest_rate_bps', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
            ],
        ),
        migrations.CreateModel(
            name='SortCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('last_account_number', models.PositiveIntegerField(default=0)),
                ('last_index', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_interest_run', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('savings', 'Savings')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('restricted', 'Restricted'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('interest_enabled', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.userprofile')),
                ('sort_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.sortcode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sort_code', 'account_number'), name='unique_account_per_sortcode')],
            },
        ),
    ]
