# Generated by Django 5.2.13 on 2026-05-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_bankaccount_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortcode',
            name='last_issued_account_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sortcode',
            name='last_issued_sortcode_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
