# Generated by Django 5.2.13 on 2026-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_bank_address_bank_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
