# Generated by Django 5.2.13 on 2026-05-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_sortcode_last_issued_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='sort_code',
        ),
    ]
