# Generated by Django 5.2.13 on 2026-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bank_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='monthly_deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
