# Generated by Django 5.2.13 on 2026-05-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bank_monthly_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSortCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.PositiveIntegerField()),
                ('end_range', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortCodeAllocator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_block', models.PositiveIntegerField(default=0)),
                ('end_block', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bank',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.TextField(max_length=600, verbose_name='Bank description'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Bank name'),
        ),
        migrations.CreateModel(
            name='SortCodeAllocatorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('start_range', models.PositiveIntegerField()),
                ('end_range', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank')),
            ],
        ),
    ]
