# Generated by Django 5.2.13 on 2026-05-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_availablesortcode_sortcodeallocator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availablesortcode',
            name='is_available',
        ),
    ]
