# Generated by Django 5.2.13 on 2026-05-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_bankaccount_last_updated_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortcode',
            old_name='sort_code',
            new_name='external_sort_code',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='bank.sortcode'),
        ),
    ]
