# Generated by Django 5.2.13 on 2026-05-11 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_sort_code_sortcode_external_sort_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortcode',
            name='block_end',
        ),
        migrations.RemoveField(
            model_name='sortcode',
            name='block_start',
        ),
        migrations.RemoveField(
            model_name='sortcode',
            name='last_issued_account_number',
        ),
        migrations.RemoveField(
            model_name='sortcode',
            name='last_issued_sortcode_number',
        ),
        migrations.AddField(
            model_name='sortcodeallocationstate',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
        migrations.AddField(
            model_name='sortcodeallocationstate',
            name='last_issued_account_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sortcodeallocationstate',
            name='last_issued_sortcode_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='sort_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='bank.sortcode'),
        ),
    ]
