# Generated by Django 5.2.13 on 2026-05-09 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_remove_availablesortcode_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSortCodeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.PositiveBigIntegerField()),
                ('end_range', models.PositiveBigIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claimed_on', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank')),
            ],
        ),
        migrations.CreateModel(
            name='SortCodeAllocationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_range', models.PositiveBigIntegerField(default=0)),
                ('end_range', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SortCodeAllocationStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank')),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableSortCode',
        ),
        migrations.DeleteModel(
            name='SortCodeAllocator',
        ),
        migrations.RemoveField(
            model_name='sortcode',
            name='last_account_number',
        ),
        migrations.RemoveField(
            model_name='sortcode',
            name='last_index',
        ),
        migrations.AddField(
            model_name='sortcode',
            name='block_end',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sortcode',
            name='block_start',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sortcode',
            name='last_issued_account_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SortCodeAllocatorLog',
        ),
    ]
