# Generated by Django 5.2.13 on 2026-05-11 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_sortcode_block_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.FileField(null=True, upload_to='bank/logo/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Bank logo'),
        ),
    ]
