# Generated by Django 5.2.13 on 2026-05-09 01:35

import django.core.validators
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_availablesortcoderange_sortcodeallocationstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='identifier',
        ),
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='interest_rate_bps',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='bank/logo/'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='offer_overdraft',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
        migrations.AlterField(
            model_name='bank',
            name='offer_saving_account',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
