# Generated by Django 5.2.13 on 2026-05-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_bank_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortcodeallocationstate',
            name='bank',
        ),
    ]
