# Generated by Django 5.2.13 on 2026-05-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_remove_bank_identifier_bank_bank_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortcode',
            name='code',
        ),
        migrations.AddField(
            model_name='sortcode',
            name='sort_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
