# Generated by Django 5.2.13 on 2026-05-09 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_remove_sortcode_code_sortcode_sort_code'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortcode',
            old_name='last_issued_account_number',
            new_name='last_issued_sortcode_number',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('savings', 'Savings')], default='basic', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user_profile.userprofile'),
        ),
    ]
