# Generated by Django 5.2.13 on 2026-05-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_remove_sortcodeallocationstate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortcodeallocationstate',
            name='bank',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sortcode_allocator', to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='sortcode',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sort_codes', to='bank.bank'),
        ),
    ]
