# Generated by Django 5.2.13 on 2026-05-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_sortcodeallocationstate_bank_alter_sortcode_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortCodeAllocatorLastRecordLookup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_size', models.PositiveBigIntegerField()),
                ('start_range', models.PositiveBigIntegerField(default=0)),
                ('end_range', models.PositiveBigIntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
