# Generated by Django 5.2.13 on 2026-05-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_rename_last_issued_account_number_sortcode_last_issued_sortcode_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortcode',
            name='last_issued_sortcode_number',
            field=models.PositiveBigIntegerField(default=models.PositiveBigIntegerField(default=0)),
        ),
    ]
