# Generated by Django 5.2.13 on 2026-05-09 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_sortcode_last_issued_sortcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortcode',
            name='last_issued_sortcode_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
