# Generated by Django 5.2.13 on 2026-05-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_sortcodeallocatorlastrecordlookup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortcodeallocatorlastrecordlookup',
            name='singleton_key',
            field=models.BooleanField(default=True, editable=False, unique=True),
        ),
    ]
