# Generated by Django 5.2.13 on 2026-05-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_sortcodeallocatorlastrecordlookup_singleton_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sortcoderangepool',
            options={'verbose_name_plural': 'Sortcode range pool'},
        ),
    ]
