# Generated by Django 5.2.13 on 2026-05-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_alter_sortcode_last_issued_sortcode_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortcode',
            name='sort_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
