# Generated by Django 5.2.13 on 2026-05-09 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_sortcode_sort_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortcode',
            name='sort_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
