# Generated by Django 5.2.13 on 2026-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_sortcode_sort_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortcodeallocationstatelog',
            name='end_range',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sortcodeallocationstatelog',
            name='start_range',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
