# Generated by Django 5.2.13 on 2026-05-22 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_bank_offer_loans_alter_bank_id_alter_bankaccount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Interest rate (%)*'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='interest_rate_bps',
            field=models.PositiveIntegerField(default=0, help_text='Annual interest rate in basis points (bps). 100 bps = 1%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
