# Generated by Django 5.2.13 on 2026-05-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_sortcodeallocationstatelog_end_range_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableSortCodeRange',
            new_name='SortCodeRangePool',
        ),
        migrations.AddField(
            model_name='sortcodeallocationstate',
            name='block_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
