# Generated by Django 5.2.13 on 2026-05-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_bank_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='interest_rate',
        ),
    ]
