# Generated by Django 5.2.13 on 2026-05-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_remove_bank_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='source',
            field=models.CharField(choices=[('Seeded', 'Seeded'), ('Admin', 'Admin')], default='Admin', max_length=10),
        ),
    ]
