# Generated by Django 5.2.13 on 2026-08-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0018_ledgerentry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="currency",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Bank transfer"),
                    ("INTERNAL_TRANSFER", "Internal transfer"),
                    ("EXTERNA", "External"),
                    ("CARD", "Card"),
                ],
                max_length=25,
            ),
        ),
    ]
