# Generated by Django 5.2.13 on 2026-08-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0019_alter_ledgerentry_currency_alter_ledgerentry_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="review_required",
            field=models.BooleanField(default=False),
        ),
    ]
