# Generated by Django 5.2.13 on 2026-08-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0020_ledgerentry_review_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgerentry",
            options={
                "verbose_name": "Ledger entry",
                "verbose_name_plural": "Ledger entries",
            },
        ),
    ]
