# Generated by Django 5.2.13 on 2026-09-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0022_accountsecuritysettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountsecuritysettings",
            options={"verbose_name_plural": "Account Security Settings"},
        ),
    ]
