# Generated by Django 5.2.13 on 2026-09-12 13:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0023_alter_accountsecuritysettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="overdraft_limit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
