# Generated by Django 5.2.13 on 2026-09-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0024_bankaccount_overdraft_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
