# Generated by Django 5.2.13 on 2026-09-13 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0025_ledgerentry_transaction_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ledgerentry",
            old_name="transaction_id",
            new_name="transaction_reference",
        ),
    ]
