# Generated by Django 5.2.13 on 2026-09-13 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0026_rename_transaction_id_ledgerentry_transaction_reference"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ledgerentry",
            old_name="transaction_reference",
            new_name="transfer_reference",
        ),
    ]
