# Generated by Django 5.2.13 on 2026-09-15 20:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0027_rename_transaction_reference_ledgerentry_transfer_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="reserved_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
