# Generated by Django 5.2.13 on 2026-09-15 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0028_bankaccount_reserved_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="currency",
            field=models.CharField(default="GBP", max_length=3),
        ),
    ]
