# Generated by Django 5.2.13 on 2026-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0029_bankaccount_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="notes",
            field=models.CharField(
                blank=True, editable=False, max_length=255, null=True
            ),
        ),
    ]
