# Generated by Django 5.2.13 on 2026-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0030_ledgerentry_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
