# Generated by Django 5.2.13 on 2026-05-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.CharField(max_length=128),
        ),
    ]
