# Generated by Django 5.2.13 on 2026-05-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_pin_is_active_alter_pin_pin'),
        ('user_profile', '0004_alter_userprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='user_profile.userprofile'),
        ),
    ]
