from django.core.management.base import BaseCommand
from bank.services import BankProvisioningService


from decimal import Decimal

BANK_SEED_DATA = [
    {
        "name": "Atlas Aurora National Bank",
        "country": "GB",
        "description": "A modern digital-first bank focusing on personal banking and flexible savings solutions.",
        "logo": "banks/logo/atlas-bank.png",
        "branch_name": "London Central Branch",
        "address_line_1": "12 King Street",
        "address_line_2": "Westminster",
        "post_code": "SW1A 1AA",
        "interest_period": "MONTHLY",
        "phone_number": "+44 20 7946 0123",
        "minimum_opening_deposit": Decimal("0.00"),
        "offer_overdraft": "Yes",
         "offer_loans": "No",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("0.00"),
    },
    {
        "name": "Elm Financial Crown & Vale Bank",
        "country": "GB",
        "description": "Traditional banking institution offering premium accounts and high-street services.",
        "logo": "banks/logo/elm-financial.png",
        "branch_name": "Manchester Main Branch",
        "address_line_1": "88 Deansgate",
        "address_line_2": "City Centre",
        "post_code": "M3 2QG",
        "interest_period": "MONTHLY",
        "phone_number": "+44 161 555 0199",
        "minimum_opening_deposit": Decimal("0.00"),
        "offer_overdraft": "Yes",
        "offer_saving_account": "Yes",
         "offer_loans": "No",
        "monthly_deposit": Decimal("150.00"),
    },
    {
        "name": "Harbour Trust Bank",
        "country": "GB",
        "description": "Focused on business accounts and SME financial services across Europe.",
        "logo": "banks/logo/harbour-trust.png",
        "branch_name": "Birmingham Business Hub",
        "address_line_1": "45 Colmore Row",
        "address_line_2": "Birmingham Business District",
        "post_code": "B3 2BS",
        "interest_period": "MONTHLY",
        "phone_number": "+44 121 496 7740",
        "minimum_opening_deposit": Decimal("250.00"),
        "offer_overdraft": "Yes",
        "offer_saving_account": "No",
        "monthly_deposit": Decimal("500.00"),
    },
    {
        "name": "Lumen Financial",
        "country": "GB",
        "description": "A stable banking provider offering conservative savings and long-term investment accounts.",
        "logo": "banks/logo/lumen.png",
        "branch_name": "Leeds Financial Centre",
        "address_line_1": "3 Park Square East",
        "address_line_2": "Leeds City Centre",
        "post_code": "LS1 2NE",
        "interest_period": "YEARLY",
        "phone_number": "+44 113 322 8890",
        "minimum_opening_deposit": Decimal("500.00"),
        "offer_overdraft": "No",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("200.00"),
    },
    {
        "name": "Nova Credit Digital Bank",
        "country": "GB",
        "description": "A fully digital bank offering instant accounts and AI-driven financial insights.",
        "logo": "banks/logo/nova-credit.png",
        "branch_name": "Digital HQ",
        "address_line_1": "1 Silicon Court",
        "address_line_2": "Tech City",
        "post_code": "EC1Y 8SY",
        "interest_period": "MONTHLY",
        "phone_number": "+44 20 7000 9001",
        "minimum_opening_deposit": Decimal("1.00"),
        "offer_overdraft": "Yes",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("50.00"),
    },
    {
        "name": "Pulse Oakshire Bank",
        "country": "GB",
        "description": "Community-focused bank supporting local businesses and personal savings growth.",
        "logo": "banks/logo/pulse.png",
        "branch_name": "Oxford Branch",
        "address_line_1": "22 High Street",
        "address_line_2": "Oxford",
        "post_code": "OX1 4AH",
        "interest_period": "MONTHLY",
        "phone_number": "+44 1865 770 220",
        "minimum_opening_deposit": Decimal("0.00"),
        "offer_overdraft": "No",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("0.00"),
    },
    {
        "name": "Riverline Vertex Banking Group",
        "country": "GB",
        "description": "High-tier financial institution specialising in investment banking and wealth management.",
        "logo": "banks/logo/riverline.png",
        "branch_name": "Canary Wharf Tower",
        "address_line_1": "25 Canada Square",
        "address_line_2": "Canary Wharf",
        "post_code": "E14 5LQ",
        "interest_period": "YEARLY",
        "phone_number": "+44 20 7123 4567",
        "minimum_opening_deposit": Decimal("1000.00"),
        "offer_overdraft": "Yes",
         "offer_loans": "No",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("1000.00"),

    },
    {
        "name": "Steadfast Pioneer Mutual Bank",
        "country": "GB",
        "description": "Ethical mutual bank prioritising customer ownership and fair interest rates.",
        "logo": "banks/logo/steadfast.png",
        "branch_name": "Liverpool Branch",
        "address_line_1": "10 Castle Street",
        "address_line_2": "Liverpool",
        "post_code": "L2 0NE",
        "interest_period": "MONTHLY",
        "phone_number": "+44 151 233 4455",
        "minimum_opening_deposit": Decimal("0.00"),
        "offer_overdraft": "No",
         "offer_loans": "No",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("0.00"),
    },
    {
        "name": "Urban BlueHarbour Bank",
        "country": "GB",
        "description": "Modern coastal-inspired bank offering lifestyle banking and travel-friendly accounts.",
        "logo": "banks/logo/urban-bank.png",
        "branch_name": "Brighton Branch",
        "address_line_1": "77 Marine Parade",
        "address_line_2": "Brighton",
        "post_code": "BN2 1TA",
        "interest_period": "MONTHLY",
        "phone_number": "+44 1273 889 100",
        "minimum_opening_deposit": Decimal("20.00"),
        "offer_overdraft": "Yes",
        "offer_loans": "No",
        "offer_saving_account": "Yes",
        "monthly_deposit": Decimal("60.00"),
    },
]


class Command(BaseCommand):

    def handle(self, *args, **kwargs):

        for bank_data in BANK_SEED_DATA:
            BankProvisioningService.create_bank(bank_data)

        self.stdout.write(self.style.SUCCESS("Banks seeded successfully"))