# Generated by Django 5.2.13 on 2026-07-25 21:19

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bank", "0017_bank_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=32)),
                ("card_number", models.CharField(max_length=32, unique=True)),
                (
                    "expiry_date",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "card_brand",
                    models.CharField(
                        choices=[
                            ("visa", "Visa"),
                            ("mastercard", "Mastercard"),
                            ("discover", "Discover"),
                        ],
                        default="visa",
                        max_length=20,
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        choices=[
                            ("virtual", "Virtual"),
                            ("physical", "Physical"),
                            ("temporary", "Temporary"),
                        ],
                        default="virtual",
                        max_length=20,
                    ),
                ),
                (
                    "card_category",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        default="debit",
                        max_length=20,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified_on", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="bank.bankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
    ]
