# Generated by Django 5.2.13 on 2026-07-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcard",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
