# Generated by Django 5.2.13 on 2026-07-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0017_bank_source"),
        ("card", "0002_bankcard_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcard",
            name="show_in_dashboard",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CardDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_cards_to_show", models.PositiveSmallIntegerField(default=3)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_modified_on", models.DateTimeField(auto_now=True)),
                (
                    "bank_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bank.bankaccount",
                    ),
                ),
            ],
        ),
    ]
