# Generated by Django 5.2.13 on 2026-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0003_bankcard_show_in_dashboard_carddashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcard",
            name="card_id",
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
