# Generated by Django 5.2.13 on 2026-08-01 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0017_bank_source"),
        ("card", "0004_bankcard_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carddashboard",
            name="bank_account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_cards",
                to="bank.bankaccount",
            ),
        ),
    ]
