# Generated by Django 5.2.13 on 2026-08-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0005_alter_carddashboard_bank_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankcard",
            name="default_card",
            field=models.BooleanField(default=False),
        ),
    ]
