# Generated by Django 5.2.13 on 2026-08-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0006_bankcard_default_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankcard",
            name="balance",
        ),
    ]
