# Generated by Django 5.2.13 on 2026-04-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(db_index=True, max_length=100)),
                ('to_email', models.EmailField(db_index=True, max_length=200)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
                ('email_body', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('to', models.CharField(max_length=200)),
                ('from_user', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
