# Generated by Django 5.2.13 on 2026-04-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_emaillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillog',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='to',
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
