# Generated by Django 5.2.13 on 2026-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_emaillog_from_user_remove_emaillog_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='num_of_resends',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verification',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
