# Generated by Django 5.2.13 on 2026-04-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_verification_num_of_resends_verification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='deletion_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='verification',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
