# Generated by Django 5.2.13 on 2026-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_verification_deletion_scheduled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='verification_type',
            field=models.CharField(choices=[('EV', 'Email Verification'), ('PV', 'Password Verification'), ('PR', 'Password Reset'), ('AC', 'Account Activation')], default='EV', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='verification',
            constraint=models.UniqueConstraint(fields=('user', 'verification_type'), name='unique_user_verification_type'),
        ),
    ]
