# Generated by Django 5.2.13 on 2026-05-02 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_verification_verification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Success'), ('E', 'Expired'), ('B', 'Blocked')], default='P', max_length=1),
        ),
    ]
