# Generated by Django 5.2.13 on 2026-05-02 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_verification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationBlock',
            fields=[
            ],
            options={
                'verbose_name': 'Blocked Verification',
                'verbose_name_plural': 'Blocked Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.verification',),
        ),
        migrations.CreateModel(
            name='VerificationExpired',
            fields=[
            ],
            options={
                'verbose_name': 'Expired Verification',
                'verbose_name_plural': 'Expired Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.verification',),
        ),
        migrations.CreateModel(
            name='VerificationPending',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Verification',
                'verbose_name_plural': 'Pending Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.verification',),
        ),
        migrations.CreateModel(
            name='VerificationUsed',
            fields=[
            ],
            options={
                'verbose_name': 'Used Verification',
                'verbose_name_plural': 'Used Verifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.verification',),
        ),
        migrations.RenameField(
            model_name='verification',
            old_name='num_of_resends',
            new_name='num_of_resend_requests',
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Verified'), ('E', 'Expired'), ('B', 'Blocked')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
