# Generated by Django 5.2.13 on 2026-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_verificationblock_verificationexpired_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='verification_type',
            field=models.CharField(choices=[('EV', 'Email Verification'), ('PV', 'Password Verification'), ('PR', 'Password Reset')], default='EV', max_length=2),
        ),
    ]
