# Generated by Django 5.2.13 on 2026-07-04 17:43

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profile', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequestBasicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Bank Country*')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], max_length=20)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('special_requests', models.TextField(blank=True, max_length=500, null=True)),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical'), ('temporary', 'Temporary')], default='virtual', max_length=20)),
                ('card', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=20)),
                ('card_brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover')], default='visa', max_length=20)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_requests', to='user_profile.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CardRequestEmploymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('intern', 'Intern'), ('self_employed', 'Self-employed')], max_length=20)),
                ('years_of_employment', models.CharField(choices=[('less_than_one', 'Less than 1 year'), ('one_to_three', '1-3 years'), ('three_to_five', '3-5 years'), ('five_to_ten', '5-10 years'), ('more_than_ten', 'More than 10 years')], max_length=20)),
                ('annual_income_range', models.CharField(choices=[('less_than_15k', 'Less than 15,000'), ('from_15k_to_24k', '15,000 - 24,000'), ('from_24k_to_34k', '24,000 - 34,000'), ('from_34k_to_44k', '34,000 - 44,000'), ('from_44k_to_54k', '44,000 - 54,000'), ('from_54k_to_64k', '54,000 - 64,000'), ('from_64k_to_74k', '64,000 - 74,000'), ('from_74k_to_84k', '74,000 - 84,000'), ('from_84k_to_94k', '84,000 - 94,000'), ('from_94k_to_104k', '94,000 - 104,000'), ('higher_than_104k', 'Higher than 104,000')], max_length=20)),
                ('pay_frequency', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('semi_monthly', 'Semi-monthly'), ('monthly', 'Monthly'), ('annually', 'Annually')], max_length=20)),
                ('contract_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporary'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('intern', 'Intern'), ('agency_worker', 'Agency Worker')], max_length=20)),
                ('card_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_information', to='card_request.cardrequestbasicinformation')),
            ],
        ),
    ]
