# Generated by Django 5.2.13 on 2026-07-05 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrequestbasicinformation',
            name='employer_name',
        ),
        migrations.RemoveField(
            model_name='cardrequestbasicinformation',
            name='employment_status',
        ),
        migrations.AddField(
            model_name='cardrequestbasicinformation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardrequestbasicinformation',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='Addess line 1*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='card',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=20, verbose_name='Card*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='card_brand',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('discover', 'Discover')], default='visa', max_length=20, verbose_name='Card brand*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='card_type',
            field=models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical'), ('temporary', 'Temporary')], default='virtual', max_length=20, verbose_name='Card type*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Email*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Post code*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='special_requests',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Special instructions'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='state',
            field=models.CharField(max_length=100, verbose_name='State*'),
        ),
    ]
