# Generated by Django 5.2.13 on 2026-07-05 16:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0002_remove_cardrequestbasicinformation_employer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardrequestemploymentinformation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardrequestemploymentinformation',
            name='last_modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
