# Generated by Django 5.2.13 on 2026-07-07 10:31

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0003_cardrequestemploymentinformation_created_on_and_more'),
        ('user_profile', '0006_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequestAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('terms_of_condition', models.TextField(help_text='Maximum 4,000 characters (around 2800-4000 words).', validators=[django.core.validators.MaxLengthValidator(20000)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cardrequestemploymentinformation',
            name='employer_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Employer name *'),
        ),
        migrations.AddField(
            model_name='cardrequestemploymentinformation',
            name='uaer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_request_employments', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Phone number*'),
        ),
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_request_basic_information', to='user_profile.userprofile'),
        ),
        migrations.AlterField(
            model_name='cardrequestemploymentinformation',
            name='employment_status',
            field=models.CharField(choices=[('employed', 'Employed'), ('unemployed', 'Unemployed')], max_length=20, verbose_name='Employer status*'),
        ),
    ]
