# Generated by Django 5.2.13 on 2026-07-07 16:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0004_cardrequestagreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequestagreement',
            name='terms_of_condition',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
