# Generated by Django 5.2.13 on 2026-07-07 16:44

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0005_alter_cardrequestagreement_terms_of_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequestagreement',
            name='terms_of_condition',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Terms of conditions'),
        ),
        migrations.AlterField(
            model_name='cardrequestagreement',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
