# Generated by Django 5.2.13 on 2026-07-08 15:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0006_alter_cardrequestagreement_terms_of_condition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequestApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now_add=True)),
                ('review_on', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('reviewed_by', models.CharField(max_length=40)),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cardrequestbasicinformation',
            name='CardRequestApplication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_information', to='card_request.cardrequestapplication'),
        ),
        migrations.AlterField(
            model_name='cardrequestemploymentinformation',
            name='card_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_information', to='card_request.cardrequestapplication'),
        ),
    ]
