# Generated by Django 5.2.13 on 2026-07-08 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0007_cardrequestapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequestbasicinformation',
            old_name='CardRequestApplication',
            new_name='card_request_applicaton',
        ),
        migrations.AlterField(
            model_name='cardrequestapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_card_applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
