# Generated by Django 5.2.13 on 2026-07-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0008_rename_cardrequestapplication_cardrequestbasicinformation_card_request_applicaton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardrequestbasicinformation',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='cardrequestemploymentinformation',
            name='uaer_profile',
        ),
    ]
