# Generated by Django 5.2.13 on 2026-07-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0009_remove_cardrequestbasicinformation_user_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequestbasicinformation',
            old_name='card_request_applicaton',
            new_name='card_request_application',
        ),
    ]
