# Generated by Django 5.2.13 on 2026-07-09 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0010_rename_card_request_applicaton_cardrequestbasicinformation_card_request_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequestemploymentinformation',
            old_name='card_request',
            new_name='card_request_application',
        ),
        migrations.CreateModel(
            name='CardRequestApplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('status_changed', 'Status Changed'), ('review_completed', 'Review Completed'), ('notes_added', 'Notes Added')], max_length=25)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
