# Generated by Django 5.2.13 on 2026-07-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0011_rename_card_request_cardrequestemploymentinformation_card_request_application_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequestbasicinformation',
            old_name='card_request_application',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='cardrequestemploymentinformation',
            old_name='card_request_application',
            new_name='application',
        ),
    ]
