# Generated by Django 5.2.13 on 2026-07-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0012_rename_card_request_application_cardrequestbasicinformation_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequestapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
