# Generated by Django 5.2.13 on 2026-07-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0013_alter_cardrequestapplication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardrequestapplication',
            old_name='review_on',
            new_name='reviewed_on',
        ),
    ]
