# Generated by Django 5.2.13 on 2026-07-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0014_rename_review_on_cardrequestapplication_reviewed_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email*'),
        ),
    ]
