# Generated by Django 5.2.13 on 2026-07-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0015_alter_cardrequestbasicinformation_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRequestApplicationAccepted',
            fields=[
            ],
            options={
                'verbose_name': 'Accepted application',
                'verbose_name_plural': 'Accepted applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('card_request.cardrequestapplication',),
        ),
        migrations.CreateModel(
            name='CardRequestApplicationCancelled',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled application',
                'verbose_name_plural': 'Cancelled applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('card_request.cardrequestapplication',),
        ),
        migrations.CreateModel(
            name='CardRequestApplicationPending',
            fields=[
            ],
            options={
                'verbose_name': 'Pending application',
                'verbose_name_plural': 'Pending applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('card_request.cardrequestapplication',),
        ),
        migrations.CreateModel(
            name='CardRequestApplicationRejected',
            fields=[
            ],
            options={
                'verbose_name': 'Rejected application',
                'verbose_name_plural': 'Rejected applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('card_request.cardrequestapplication',),
        ),
        migrations.CreateModel(
            name='CardRequestApplicationWithdrawn',
            fields=[
            ],
            options={
                'verbose_name': 'Withdrawn application',
                'verbose_name_plural': 'Withdrawn applications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('card_request.cardrequestapplication',),
        ),
        migrations.AlterModelOptions(
            name='cardrequestbasicinformation',
            options={'verbose_name': 'Card request basic information', 'verbose_name_plural': 'Card request basic information'},
        ),
        migrations.AlterModelOptions(
            name='cardrequestemploymentinformation',
            options={'verbose_name': 'Card request employment detail', 'verbose_name_plural': 'Card request employment details'},
        ),
    ]
