# Generated by Django 5.2.13 on 2026-07-12 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_request', '0016_cardrequestapplicationaccepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrequestbasicinformation',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basic_information', to='card_request.cardrequestapplication'),
        ),
    ]
