# Generated by Django 5.2.13 on 2026-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_request", "0017_alter_cardrequestbasicinformation_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardrequestapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("On_holding", "On Hold"),
                    ("Accepted", "Accepted"),
                    ("Rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
