# Generated by Django 5.2.13 on 2026-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_request", "0018_alter_cardrequestapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardrequestapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("on_holding", "On Hold"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                    ("cancelled", "Cancelled"),
                    ("under_review", "Under Review"),
                ],
                default="pending",
                max_length=15,
            ),
        ),
    ]
