# Generated by Django 5.2.13 on 2026-07-17 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_request", "0019_alter_cardrequestapplication_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cardrequestapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("user",),
                name="unique_pending_application_per_user",
            ),
        ),
    ]
