# Generated by Django 5.2.13 on 2026-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_request", "0021_alter_cardrequestapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardrequestapplication",
            name="application_id",
            field=models.CharField(
                blank=True, editable=False, max_length=32, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="cardrequestapplicationlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("application_submitted", "Application Submitted"),
                    ("status_changed", "Status Changed"),
                    ("review_completed", "Review Completed"),
                    ("notes_added", "Notes Added"),
                    ("application_deleted", "Application Deleted"),
                ],
                max_length=25,
            ),
        ),
    ]
