# Generated by Django 5.2.13 on 2026-05-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_middle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer_not_to_say', 'Prefer not to say')], default='Prefer_not_to_say', max_length=20, null=True),
        ),
    ]
