"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path
from os.path import join
from dotenv import load_dotenv
from os import getenv
from os import makedirs


load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#d(ail%aais(1v-__z54r+2!nqjj1&dw3(p$r7@paa6_^n68&e'
TEMPLATES_DIRS = BASE_DIR / "templates"


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


AUTH_USER_MODEL = 'authentication.User'



# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django_q',
    'django_countries',

    # third party django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # my apps
    'bank.apps.BankConfig',
    'wallet.apps.WalletConfig',
    'setup.apps.SetupConfig',
    'core_admin.apps.CoreAdminConfig',
    'home.apps.HomeConfig',
    'authentication.apps.AuthenticationConfig',
    'user_profile.apps.UserProfileConfig',


    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': getenv("NAME"),
        'USER': getenv('USER'),
        'PASSWORD': getenv("PASSWORD"),
        'HOST': getenv("HOST"),
        'PORT': getenv("PORT"),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    join(BASE_DIR, 'static'),
]

STATIC_ROOT = join(BASE_DIR, 'staticfiles')



Q_CLUSTER = {
    'name': 'virtualBank',
    'workers': 4,
    'recycle': 500,
    'timeout': 60,
    'compress': True,
    'save_limit': 1000,
    'queue_limit': 1000,
    'label': 'Django Q',
    'orm': "default",
}


# for now send the email to the console since we are in development, later wire it to gmail
# EMAIL BACKEND (DEV)
EMAIL_HOST   = "test@example.com"

if DEBUG:
 
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    DEFAULT_FROM_EMAIL = "Virtual Bank <no-reply@virtualbank.local>"

    EMAIL_FILE_PATH    = BASE_DIR / 'sent_emails' / 'dev'
    makedirs(EMAIL_FILE_PATH, exist_ok=True)



# -------------------------------------------------------------------
# settings.py
# -------------------------------------------------------------------

LOG_DIR = os.path.join(BASE_DIR, "logs")
makedirs(LOG_DIR, exist_ok=True)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # -------------------------
    # Formatters
    # -------------------------
    "formatters": {
        "right_indented": {
            "()": "utils.utils.RightIndentedFormatter",
            "format": "[%(asctime)s] %(levelname)-8s %(name)-13s: [%(message)s]",
        },
    },

    # -------------------------
    # Handlers
    # -------------------------
    "handlers": {
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "emails.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5MB
            "backupCount": 3,
            "formatter": "right_indented",
        },
    },

    # -------------------------
    # Loggers
    # -------------------------
    "loggers": {
        "email_sender": {
            "handlers": ["file"],  
            "level": "DEBUG",
            "propagate": False,
        },
    },

    # -------------------------
    # Root Logger (safety net)
    # -------------------------
    "root": {
        "handlers": ["file"],
        "level": "WARNING",
    },
}



LOGIN_REDIRECT_URL = '/'
LOGIN_URL           = "login_user"
LOGOUT_REDIRECT_URL = "login_user" 





# Maximum number of resend attempts allowed per user before requiring cooldown or blocking further requests
MAX_VERIFICATION_CODE_RESENDS_PER_USER  = 5

# Cooldown period (in seconds) enforced between consecutive resend requests
# Prevents users from spamming the resend endpoint
RESEND_COOLDOWN_PERIOD_IN_SECONDS  = 60

# Default lifespan (in minutes) for a verification code before it becomes invalid
DEFAULT_CODE_EXPIRY_IN_MINUTES  = 5

# Fixed size of the sort code range allocated to each bank
SORT_CODE_ALLOCATION_BLOCK = 200_000



JAZZMIN_SETTINGS = {
    "site_title": "Bank Admin",
    "site_header": "Bank Core System",
    "site_brand": "EU VirtualBank",
    "welcome_sign": "Welcome to the Banking Dashboard",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo": None,
}